// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARnBj8Z4jQu9v_sq2Org44sqhhsjG_9QA',
    appId: '1:577427516724:web:1b894224c6bc2018168961',
    messagingSenderId: '577427516724',
    projectId: 'psychtrack-812ce',
    authDomain: 'psychtrack-812ce.firebaseapp.com',
    storageBucket: 'psychtrack-812ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6orBL3hni4NsdhVYjU0mMHPI0-O0kY5Q',
    appId: '1:577427516724:android:725d3a5901cbb34d168961',
    messagingSenderId: '577427516724',
    projectId: 'psychtrack-812ce',
    storageBucket: 'psychtrack-812ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdXYAGKO2CeroqoUuViuR1Nl37mmJCQs',
    appId: '1:577427516724:ios:bfcb559cd78d067a168961',
    messagingSenderId: '577427516724',
    projectId: 'psychtrack-812ce',
    storageBucket: 'psychtrack-812ce.appspot.com',
    iosClientId:
        '577427516724-ca62ne2ri87igvhgct2bemf9k4g4k752.apps.googleusercontent.com',
    iosBundleId: 'com.example.psychtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADdXYAGKO2CeroqoUuViuR1Nl37mmJCQs',
    appId: '1:577427516724:ios:bfcb559cd78d067a168961',
    messagingSenderId: '577427516724',
    projectId: 'psychtrack-812ce',
    storageBucket: 'psychtrack-812ce.appspot.com',
    iosClientId:
        '577427516724-ca62ne2ri87igvhgct2bemf9k4g4k752.apps.googleusercontent.com',
    iosBundleId: 'com.example.psychtrack',
  );
}
